services:
  maven:
    image: maven:3.9-eclipse-temurin
    container_name: maven_build
    working_dir: /workspace
    volumes:
      - .:/workspace
    tty: true
    command: >
      sh -c "
      mvn clean install &&
      mvn test || exit 1 &&
      mvn jacoco:report;
      mvn checkstyle:check || true
      "